using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ballCamRotation : MonoBehaviour
{
    public float mouseSensitvity = 100f;

    public Transform ball;

    float xRotation = 0f;
    // Start is called before the first frame update
    void Start()
    {
        //Cursor.lockState = CursorLockMode.Locked;
    }

    // Update is called once per frame
    void Update()
    {
        float mouseX = Input.GetAxis("Mouse X") * mouseSensitvity * Time.deltaTime;
        float mouseY = Input.GetAxis("Mouse Y") * mouseSensitvity * Time.deltaTime;

        Debug.Log(mouseX);

        xRotation -= mouseY;

        xRotation = Mathf.Clamp(xRotation, -90f, 90f);

        transform.localRotation = Quaternion.Euler(xRotation, 0f, 0f);
        ball.Rotate(Vector3.up * mouseX);
    }
}
